[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
stepmint_program = "B7iMxEABREw8hkkqDHeLbUike8unc6AfifoYnL51fwFE"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "target/deploy/stepmint-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
