[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
greengait_program = "DYf1G6UEyAebNDfgkQodKUvPBAZJXMCkBtWgRMpS8SaE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "target/deploy/greengait-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
